import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const messages = await getMessages();
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body className="flex min-h-full flex-col bg-white">
        <NextIntlClientProvider messages={messages}>
          <Navbar />
          <main className="grow container mx-auto px-4 py-8">{children}</main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
