import Carousel from "@/components/Carousel";
import { Button } from "@/components/ui/button";
import { stripe } from "@/lib/stripe";
import { getMessages, getTranslations } from "next-intl/server";
import Image from "next/image";
import Link from "next/link";

export async function generateMetadata({
  params: locale,
}: {
  params: { locale: string };
}) {

  const messages = await getMessages(locale);

  const metaTitle = messages.HomePage?.metaTitle ?? "Homepage Ecommerce";
  const metaDescription = messages.HomePage?.metaDescription ?? "Homepage Ecommerce Generated by create next app";

  return {
    title: metaTitle,
    description: metaDescription,
  };
}


export default async function Home() {
  const t = await getTranslations("HomePage");

  const products = await stripe.products.list({
    expand: ["data.default_price"],
    limit: 4,
  });

  return (
    <div>
      <section className="rounded bg-neutral-100 py-8 sm:py-12">
        <div className="mx-auto grid grid-cols-1 items-center justify-items-center gap-8 px-8 sm:px-16 md:grid-cols-2">
          <div className="max-w-md space-y-4">
            <h2 className="text-3xl font-bold tracking-tight md:text-4xl">
              {t("welcome")}
            </h2>
            <p className="text-neutral-600">{t("description")}</p>
            <Button
              asChild
              variant="default"
              className="inline-flex items-center justify-center rounded-full px-6 py-3 bg-black text-white"
            >
              <Link
                href="/products"
                className="inline-flex items-center justify-center rounded-full px-6 py-3"
              >
                {t("button")}
              </Link>
            </Button>
          </div>
          <Image
            alt="Hero Image"
            src={products.data[1].images[0]}
            className="rounded-xl"
            width={450}
            height={450}
            priority
          />
        </div>
      </section>
      <section className="py-8">
        <Carousel products={products.data} />
      </section>
    </div>
  );
}
